sonar.projectKey=SriRamkumarnsetty_Carbon-Footprint-Awareness-Platform
sonar.organization=sriramkumarnsetty
sonar.projectName=Carbon-Footprint-Awareness-Platform

sonar.sources=src
sonar.tests=src/tests,e2e
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/*.test.*,**/*.spec.*

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
