/**
 * @module types/activity
 * @description Activity and goal type definitions for CarbonMind AI.
 */
import type { TimestampLike } from "./common";

/** Carbon activity categories */
export type ActivityCategory =
  | "transport"
  | "food"
  | "electricity"
  | "shopping"
  | "water"
  | "waste"
  | "lifestyle";

/** Individual carbon activity record */
export interface Activity {
  /** Document ID */
  id: string;
  /** Owner user ID */
  userId: string;
  /** Activity category */
  category: ActivityCategory;
  /** Numeric value of the activity */
  value: number;
  /** Unit of measurement (km, kWh, servings, etc.) */
  unit: string;
  /** Carbon emissions in kg CO2 */
  carbonEmit: number;
  /** Activity date */
  date: TimestampLike;
  /** Optional descriptive note */
  note?: string;
  /** Optional sub-type of the activity (e.g., gasolineCar, beef, airConditioner) */
  type?: string;
}

/** Goal status values */
export type GoalStatus = "active" | "completed" | "failed";

/** Goal category values */
export type GoalCategory =
  | "transport"
  | "food"
  | "electricity"
  | "shopping"
  | "water"
  | "waste"
  | "general";

/** Eco-friendly goal set by the user */
export interface EcoGoal {
  /** Document ID */
  id: string;
  /** Owner user ID */
  userId: string;
  /** Goal title */
  title: string;
  /** Related activity category */
  category: GoalCategory;
  /** Target reduction in kg CO2 */
  targetValue: number;
  /** Current reduction achieved in kg CO2 */
  currentValue: number;
  /** Goal deadline */
  deadline: TimestampLike;
  /** Current goal status */
  status: GoalStatus;
  /** Creation timestamp */
  createdAt: TimestampLike;
}

/** Category breakdown for analytics */
export interface CategoryBreakdown {
  /** Category name */
  category: ActivityCategory;
  /** Total carbon in kg CO2 */
  carbon: number;
  /** Percentage of total */
  percentage: number;
  /** Display color */
  color: string;
}

/** Weekly report generated by a scheduled backend job */
export interface WeeklyReport {
  /** Document ID */
  id: string;
  /** Owner user ID */
  userId: string;
  /** Week ending date */
  weekEnding: TimestampLike;
  /** Total carbon for the week in kg CO2 */
  totalCarbon: number;
  /** Category breakdown */
  categoryBreakdown: Record<string, number>;
  /** Number of activities logged */
  activityCount: number;
  /** Creation timestamp */
  createdAt: TimestampLike;
}
